# Generated by Django 2.2.9 on 2020-03-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validado', models.BooleanField(default=False, help_text='Refiere a si fue validado por la Administracion', verbose_name='Contribuyente Validado')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
            },
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('numero_documento', models.BigIntegerField(help_text='Numero de Documento', verbose_name='Numero de Documento')),
                ('primer_nombre', models.CharField(help_text='Primer Nombre', max_length=40, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(help_text='Segundo Nombre', max_length=40, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(help_text='Primer Apellido', max_length=40, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(help_text='Segundo Apellido', max_length=40, verbose_name='Segundo Apellido')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Domicilio_Constituido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(help_text='Direccion', max_length=150, verbose_name='Direccion')),
                ('numero', models.CharField(help_text='Numero', max_length=20, verbose_name='Numero')),
                ('ampliacion_descripcion', models.CharField(help_text='Ampliar Descripcion de la Direccion', max_length=250, verbose_name='Ampliacion Descripcion')),
            ],
            options={
                'verbose_name': 'Domicilio Constituido',
                'verbose_name_plural': 'Domicilio Constituido',
            },
        ),
        migrations.CreateModel(
            name='Domicilio_Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(help_text='Direccion', max_length=150, verbose_name='Direccion')),
                ('numero', models.CharField(help_text='Numero', max_length=20, verbose_name='Numero')),
                ('ampliacion_descripcion', models.CharField(help_text='Ampliar Descripcion de la Direccion', max_length=250, verbose_name='Ampliacion Descripcion')),
            ],
            options={
                'verbose_name': 'Domicilio Fiscal',
                'verbose_name_plural': 'Domicilio Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('numero_documento', models.BigIntegerField(help_text='Numero de Documento', verbose_name='Numero de Documento')),
                ('primer_nombre', models.CharField(help_text='Primer Nombre', max_length=40, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(help_text='Segundo Nombre', max_length=40, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(help_text='Primer Apellido', max_length=40, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(help_text='Segundo Apellido', max_length=40, verbose_name='Segundo Apellido')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('numero_documento', models.BigIntegerField(help_text='Numero de Documento', verbose_name='Numero de Documento')),
                ('primer_nombre', models.CharField(help_text='Primer Nombre', max_length=40, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(help_text='Segundo Nombre', max_length=40, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(help_text='Primer Apellido', max_length=40, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(help_text='Segundo Apellido', max_length=40, verbose_name='Segundo Apellido')),
                ('identificador', models.ForeignKey(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente')),
                ('pais', models.ForeignKey(help_text='Pais', on_delete=django.db.models.deletion.CASCADE, to='Base.Pais', verbose_name='Pais')),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de Documento', on_delete=django.db.models.deletion.CASCADE, to='Base.Tipo_Documento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
    ]
