# Generated by Django 2.2.9 on 2020-03-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contribuyentes', '0001_initial'),
        ('Base', '0002_auto_20200312_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='identificador',
            field=models.ForeignKey(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente'),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='pais',
            field=models.ForeignKey(help_text='Pais', on_delete=django.db.models.deletion.CASCADE, to='Base.Pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de Documento', on_delete=django.db.models.deletion.CASCADE, to='Base.Tipo_Documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domicilio_fiscal',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento', on_delete=django.db.models.deletion.CASCADE, to='Base.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='domicilio_fiscal',
            name='identificador',
            field=models.OneToOneField(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente'),
        ),
        migrations.AddField(
            model_name='domicilio_fiscal',
            name='localidad',
            field=models.ForeignKey(help_text='Localidad', on_delete=django.db.models.deletion.CASCADE, to='Base.Localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='domicilio_fiscal',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domicilio_constituido',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento', on_delete=django.db.models.deletion.CASCADE, to='Base.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='domicilio_constituido',
            name='identificador',
            field=models.OneToOneField(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente'),
        ),
        migrations.AddField(
            model_name='domicilio_constituido',
            name='localidad',
            field=models.ForeignKey(help_text='Localidad', on_delete=django.db.models.deletion.CASCADE, to='Base.Localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='domicilio_constituido',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directores',
            name='identificador',
            field=models.ForeignKey(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente'),
        ),
        migrations.AddField(
            model_name='directores',
            name='pais',
            field=models.ForeignKey(help_text='Pais', on_delete=django.db.models.deletion.CASCADE, to='Base.Pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='directores',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de Documento', on_delete=django.db.models.deletion.CASCADE, to='Base.Tipo_Documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='directores',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='identificador',
            field=models.OneToOneField(help_text='Identificador numerico del Contribuyente: RUT', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Identificador'),
        ),
        migrations.AlterUniqueTogether(
            name='representantes',
            unique_together={('identificador', 'tipo_documento', 'numero_documento', 'pais')},
        ),
        migrations.AlterUniqueTogether(
            name='propietarios',
            unique_together={('identificador', 'tipo_documento', 'numero_documento', 'pais')},
        ),
        migrations.AlterUniqueTogether(
            name='directores',
            unique_together={('identificador', 'tipo_documento', 'numero_documento', 'pais')},
        ),
    ]
