# Generated by Django 2.2.9 on 2020-03-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identificador', models.BigIntegerField(help_text='Para Empresas es el numero de RUT, para Personas Fisicas es el numero de CI', primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Correo Electronico para comunicaciones', max_length=100, verbose_name='correo electronico')),
                ('direccion', models.CharField(blank=True, help_text='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Telefono Fijo', max_length=50, null=True)),
                ('celular', models.CharField(help_text='Celular', max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('Contribuyente', 'Contribuyente'), ('Consultor', 'Consultor'), ('Funcionario', 'Funcionario'), ('Administrador', 'Administrador')], default='Contribuyente', help_text='Tipo de Usuario', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Activo')),
                ('staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('admin', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.')),
                ('solicitante', models.BooleanField(default=True)),
                ('ventanilla_unica', models.BooleanField(default=False)),
                ('coordinador_ventanilla_unica', models.BooleanField(default=False)),
                ('evaluador', models.BooleanField(default=False)),
                ('evaluador_sectorial', models.BooleanField(default=False)),
                ('coordinador_evaluador_sectorial', models.BooleanField(default=False)),
                ('aprobador_sectorial', models.BooleanField(default=False)),
                ('coordinador_aprobador_sectorial', models.BooleanField(default=False)),
                ('evaluador_comap', models.BooleanField(default=False)),
                ('control_contable', models.BooleanField(default=False)),
                ('coordinador_control_contable', models.BooleanField(default=False)),
                ('control_obra_civil', models.BooleanField(default=False)),
                ('coordinador_control_obra_civil', models.BooleanField(default=False)),
                ('control_juridico', models.BooleanField(default=False)),
                ('responsable_mef', models.BooleanField(default=False)),
                ('responsable_miem', models.BooleanField(default=False)),
                ('responsable_mgap', models.BooleanField(default=False)),
                ('responsable_mintur', models.BooleanField(default=False)),
                ('responsable_mtss', models.BooleanField(default=False)),
                ('coordinacion', models.BooleanField(default=False)),
                ('coordinacion_general', models.BooleanField(default=False)),
                ('ministerio_mef', models.BooleanField(default=False)),
                ('ministerio_miem', models.BooleanField(default=False)),
                ('ministerio_mgap', models.BooleanField(default=False)),
                ('ministerio_mintur', models.BooleanField(default=False)),
                ('ministerio_mtss', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Personas_Fisicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(help_text='Primer Nombre', max_length=50)),
                ('nombre2', models.CharField(blank=True, help_text='Segundo Nombre', max_length=50, null=True)),
                ('apellido1', models.CharField(help_text='Primer Apellido', max_length=50, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(help_text='Segundo Apellido', max_length=50, verbose_name='Segundo Apellido')),
                ('identificador', models.OneToOneField(help_text='Para Personas Fisicas es el numero de CI', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona_Fisica',
                'verbose_name_plural': 'Personas_Fisicas',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Razon Social', max_length=150)),
                ('nombre_comercial', models.CharField(help_text='Nombre Comercial', max_length=150)),
                ('domicilio_fiscal', models.CharField(help_text='Domicilio Fiscal', max_length=150)),
                ('domicilio_constituido', models.CharField(help_text='Domicilio Constituido', max_length=150)),
                ('n_bps', models.IntegerField(help_text='Numero de registro en BPS')),
                ('n_mtss', models.IntegerField(help_text='Numero de registro en MTSS')),
                ('identificador', models.OneToOneField(help_text='Para Empresas es el numero de RUT', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
            },
        ),
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=200)),
                ('key_expires', models.DateTimeField()),
                ('identificador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Activacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
