# Generated by Django 2.2.9 on 2020-03-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solicitudes', '0001_initial'),
        ('Contribuyentes', '0002_auto_20200312_2105'),
        ('Base', '0002_auto_20200312_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud143_step1b',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud143_step1',
            name='contribuyente',
            field=models.ForeignKey(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente'),
        ),
        migrations.AddField(
            model_name='solicitud143_step1',
            name='fecha_balance_datoseconomicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.FechaBalance', verbose_name='Fecha de Balance'),
        ),
        migrations.AddField(
            model_name='solicitud143_step1',
            name='tipo_contribuyente_datoseconomicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.TipoContribuyente', verbose_name='Tipo de Contribuyente'),
        ),
        migrations.AddField(
            model_name='solicitud143_step1',
            name='tipo_giro_datoseconomicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.TipoGiro', verbose_name='Tipo de Giro'),
        ),
        migrations.AddField(
            model_name='solicitud143_step1',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='solicitud143_step1b',
            unique_together={('contribuyente', 'num_expediente')},
        ),
        migrations.AlterUniqueTogether(
            name='solicitud143_step1',
            unique_together={('contribuyente', 'num_expediente')},
        ),
    ]
