# Generated by Django 2.2.9 on 2020-03-16 22:22

import Solicitudes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0002_auto_20200312_2105'),
        ('Base', '0002_auto_20200312_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solicitudes', '0002_auto_20200312_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud143_step1b',
            options={'verbose_name': 'Solicitud143_Step1b', 'verbose_name_plural': 'Solicitud143_Step1b'},
        ),
        migrations.AlterField(
            model_name='solicitud143_step1',
            name='credito_fiscal_aportes_patronales_mype',
            field=models.BooleanField(default=False, help_text='¿Aplica crédito fiscal por aportes patronales de artículo 28º?', verbose_name='¿Aplica crédito fiscal por aportes patronales de artículo 28º?'),
        ),
        migrations.CreateModel(
            name='Solicitud143_Step2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('num_expediente', models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2.Incrementar, verbose_name='Numero de Expediente')),
                ('contribuyente', models.ForeignKey(help_text='Contribuyente', on_delete=django.db.models.deletion.CASCADE, to='Contribuyentes.Contribuyente', verbose_name='Contribuyente')),
                ('ministerio_evaluador', models.ForeignKey(blank=True, help_text='Ministerio Evaluador', null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.Ministerios', verbose_name='Ministerio Evaluador')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud143_Step2',
                'verbose_name_plural': 'Solicitud143_Step2',
                'unique_together': {('contribuyente', 'num_expediente')},
            },
        ),
    ]
