# Generated by Django 2.2.9 on 2020-03-19 00:20

import Solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0004_solicitud143_step2b_solicitud143_step2c_solicitud143_step2d_solicitud143_step2e_solicitud143_step2f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud143_step1b',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2b',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2c',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2d',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2e',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud143_step2f',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitud143_step1b',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step1b.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2b',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2b.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2c',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2c.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2d',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2d.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2e',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2e.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step2f',
            name='num_expediente',
            field=models.BigIntegerField(default=Solicitudes.models.Solicitud143_Step2f.Incrementar, primary_key=True, serialize=False, verbose_name='Numero de Expediente'),
        ),
    ]
