# Generated by Django 2.2.9 on 2020-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0006_solicitud143_step3_solicitud143_step4a_solicitud143_step4b_solicitud143_step4c_solicitud143_step4d_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud143_step4a',
            name='ind_gral_empleo_cantidad_extension',
            field=models.DecimalField(decimal_places=0, help_text='Cantidad de años de extensión', max_digits=4, verbose_name='Cantidad de Extensión de Periodo'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step4b',
            name='ind_gral_exportaciones_cantidad_extension',
            field=models.DecimalField(decimal_places=0, help_text='Cantidad de años de extensión', max_digits=4, verbose_name='Cantidad de Extensión de Periodo'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step4d',
            name='ind_gral_TL_cantidad_extension',
            field=models.DecimalField(decimal_places=0, help_text='Cantidad de años de extensión', max_digits=4, verbose_name='Cantidad de Extensión de Periodo'),
        ),
        migrations.AlterField(
            model_name='solicitud143_step4f',
            name='ind_gral_IDi_cantidad_extension',
            field=models.DecimalField(decimal_places=0, help_text='Cantidad de años de extensión', max_digits=4, verbose_name='Cantidad de Extensión de Periodo'),
        ),
    ]
