# Generated by Django 2.2.9 on 2020-04-25 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0002_auto_20200312_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_DocumentoPresentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Tipo de Documento', max_length=50, verbose_name='Tipo de Documento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Documento a Presentar',
                'verbose_name_plural': 'Tipo de Documento a Presentar',
            },
        ),
        migrations.CreateModel(
            name='Localizacion_Operaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Nueva Localidad', 'Nueva Localidad'), ('Localidad donde ya se realizan operaciones', 'Localidad donde ya se realizan operaciones')], default='Nueva Localidad', max_length=100, unique=True, verbose_name='Localidad Nueva/Anterior')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opciones Localizacion',
                'verbose_name_plural': 'Opciones Localizacion',
            },
        ),
        migrations.CreateModel(
            name='Listado_Puntaje_Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('departamento', models.CharField(choices=[('Artigas', 'Artigas'), ('Canelones', 'Canelones'), ('Cerro Largo', 'Cerro Largo'), ('Colonia', 'Colonia'), ('Durazno', 'Durazno'), ('Flores', 'Flores'), ('Florida', 'Florida'), ('Lavalleja', 'Lavalleja'), ('Maldonado', 'Maldonado'), ('Montevideo', 'Montevideo'), ('Paysandu', 'Paysandu'), ('Rio Negro', 'Rio Negro'), ('Rivera', 'Rivera'), ('Rocha', 'Rocha'), ('Salto', 'Salto'), ('San Jose', 'San Jose'), ('Soriano', 'Soriano'), ('Tacuarembo', 'Tacuarembo'), ('Treinta y Tres', 'Treinta y Tres')], default='Montevideo', max_length=100, verbose_name='Departamentos de Uruguay')),
                ('cap_int', models.CharField(choices=[('Capital', 'Capital'), ('Resto', 'Resto')], default='Capital', max_length=100, verbose_name='Capital/Interior')),
                ('puntaje', models.PositiveIntegerField(verbose_name='Puntaje Asignado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listado de Departamentos y Puntajes',
                'verbose_name_plural': 'Listado de Departamentos y Puntajes',
                'unique_together': {('departamento', 'cap_int')},
            },
        ),
        migrations.CreateModel(
            name='Exp_Bienes_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Bienes', 'Bienes'), ('Servicios', 'Servicios')], default='Bienes', max_length=100, verbose_name='Bienes/Servicios')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion de Exportacion')),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Porcentaje')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Exportaciones de Bienes y Servicios',
                'verbose_name_plural': 'Tipo de Exportaciones de Bienes y Servicios',
                'unique_together': {('tipo', 'descripcion')},
            },
        ),
    ]
