# Generated by Django 2.2.9 on 2020-03-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.BigIntegerField(blank=True, null=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(help_text='Es la Fecha de la Cotizacion', verbose_name='Fecha')),
                ('moneda', models.IntegerField(help_text='Es el codigo BCU de la Moneda', verbose_name='Moneda')),
                ('nombre', models.CharField(help_text='Es el Nombre de la Moneda', max_length=50, verbose_name='Nombre')),
                ('codigo_ISO', models.CharField(help_text='Es el codigo ISO de la Moneda', max_length=4, verbose_name='CodigoISO')),
                ('emisor', models.CharField(help_text='Es el Pais Emisor de la Moneda', max_length=20, verbose_name='Emisor')),
                ('tcc', models.DecimalField(decimal_places=6, help_text='Es la cotizacion del Tipo de Cambio Comprador', max_digits=20, verbose_name='TCC')),
                ('tcv', models.DecimalField(decimal_places=6, help_text='Es la cotizacion del Tipo de Cambio Vendedor', max_digits=20, verbose_name='TCV')),
                ('arbact', models.DecimalField(decimal_places=6, help_text='Arbitraje', max_digits=20, verbose_name='ArbAct')),
                ('forma_arbitrar', models.IntegerField(help_text='Forma de Arbitrar: 0 = Unidad de Moneda por Dolares EEUU 1 = Dolares de EEUU por Unidad de Moneda', verbose_name='FormaArbitrar')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'unique_together': {('fecha', 'moneda', 'nombre')},
            },
        ),
    ]
